version: "3.9"
services:
  app:
    image: leoff00/tapagobot:latest
    container_name: tapago
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SENSITIVE_TOKEN: ${SENSITIVE_TOKEN}
      MODS_ID: ${MODS_ID}
      ENV: ${ENV}
    volumes:
      - ./db:/app/db 
    ports:
      - 4000:4000
    restart: on-failure


