name: golangci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build and Push docker image
        run: |
          docker buildx create --use --name bot_builder
          docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/tapagobot --platform=linux/amd64,linux/arm64 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tapagobot:latest
